# -*- coding: UTF-8 -*-
CATEGORIES = [
	{
		'name':'Celulares y Accesorios',
		'tags':[
			'Celulares',
			'Smartphones',
			'Accesorios',
			'Adaptadores de estereo',
			'Antenas',
			'Baterias',
			'Bocinas',
			'Cables de datos USB',
			'Caratulas',
			'Cargadores',
			'Chips',
			'Colgantes',
			'Colguijes',
			'Fundas',
			'Clips',
			'Lapiz optico',
			'Manos Libres',
			'Micas',
			'Pantallas',
			'Displays',
			'Otros',
			'Stylus',
			'Square',
			'Teclado',
			'Teclado bluetooth',
			'Teclado inalambrico',
			'Antena',
			'Antenas',
			'Chip',
			'Hands free',
			'Adaptadores de estereo',
			'Adaptadores USB inalambricos',
			'Flex',
		]
	},
	{
		'name':'Coleccionables',
		'tags':[
			'Comics',
			'Arte',
			'Otros ',
			'Fotografias',
			'Monedas y billetes',
			'Piedras, fosiles y otros',
			'Tarjetas',
			'Aerografos',
			'Aeromodelismo',
			'Anime',
			'Armas',
			'Articulos de coca-cola',
			'Autmoviles',
			'Automodelismo',
			'Baiseball',
			'Barbie',
			'Baseball',
			'Basquetball',
			'Billetes',
			'Boinas',
			'Bordados',
			'botellas',
			'Cajetillas de cigarros',
			'camiones',
			'Cartas',
			'Cartas',
			'carteles',
			'Cascos',
			'Ceniceros',
			'Cine',
			'coca-cola',
			'Cuchillos',
			'Dagas',
			'Elfos',
			'Encendedores',
			'Espadas',
			'Estampas',
			'Ferromodelismo',
			'Figuras',
			'football',
			'football americano',
			'Fotografias',
			'futbol',
			'futbol americano',
			'Gorras',
			'Hadas',
			'Hello Kitty',
			'Indumentaria',
			'Insignias',
			'Katanas',
			'latas',
			'Libros',
			'llaveros',
			'Lucha Libre',
			'Lucha libre mexicana',
			'Manga',
			'Maquinaria',
			'Marvel',
			'Medallas',
			'Memorabilia',
			'Militaria',
			'Modelismo Naval',
			'Monedas',
			'Motos',
			'muñecos',
			'Navajas',
			'Naves',
			'Peliculas',
			'Pick ups',
			'Pipas',
			'Plastimodelismo',
			'Ponchados',
			'Revistas',
			'Rompecabezas',
			'Scalextric',
			'Series',
			'soccer',
			'Spawn',
			'Starwars',
			'Super heroes',
			'Tarjetas telefonicas',
			'TV',
			'Vehiculos en miniatura',
			'Vehiculos militares',
			'Videojuegos',
			'WWE',
			'Yu-Gi-Oh!',
			'Yugioh',
		]
	},
	{
		'name':'Computacion y Accesorios',
		'tags':[
			'Accesorios de computacion',
			'Accesorios y repuestos',
			'Audifonos',
			'Baterias',
			'Bocinas',
			'Cables y conectores',
			'Cargadores',
			'Cartuchos y tintas',
			'Computadora de escritorio',
			'Disco duro ',
			'DVD',
			'Impresora toner',
			'Impresoras',
			'Impresoras laser',
			'Laptops',
			'Limpieza de PC',
			'Mouses',
			'Multifuncionales',
			'Netbooks',
			'Otros ',
			'Palms',
			'Quemadores',
			'Software y juegos',
			'Tarjeta madre',
			'Tarjetas de sonido',
			'Teclados',
			'USB',
			'Webcams',
			'Acces Points',
			'accesorios',
			'Acer',
			'Adaptadores Bluetooth',
			'Adaptadores USB inalambricos',
			'AMD Athlon',
			'AMD Phenom',
			'AMD Sempron',
			'Antenas',
			'Antivirus',
			'Apple',
			'Armadas',
			'Bisagras',
			'Cables',
			'Camara Web',
			'Candados de seguridad',
			'Cartuchos',
			'CD',
			'CDs Virgenes',
			'Cilindros',
			'Cintas',
			'Compaq',
			'Conectores',
			'Controles',
			'Controles para juegos',
			'Controles remotos',
			'Coolers',
			'Dell',
			'Diademas',
			'Discos duros removibles',
			'Diseño',
			'Displays',
			'DVDs virgenes',
			'Enfriadores',
			'Ensambladas',
			'Escanners',
			'Fax',
			'Filtros para monitores',
			'Floppy',
			'Fuentes de poder',
			'Gabinetes',
			'Gateway',
			'Herramientas de productividad',
			'HP',
			'Hubs',
			'IBM',
			'Intel Celeron',
			'Intel Core 2 Duo',
			'Intel Core 2 Quad',
			'Intel Core i3',
			'Intel Core i5',
			'Intel Core i7',
			'Intel Pentium II',
			'Intel Premium 4',
			'Intel Premium D',
			'Intel Premium III',
			'Intel Xeon',
			'Inverters',
			'Inyeccion de tinta',
			'Joystick',
			'Juegos para PC',
			'Lamparas',
			'Laser blanco',
			'Laser color',
			'Laser negro',
			'Lector de CD',
			'Lector de DVD',
			'Lectores de códigos de barras',
			'Maletines',
			'Matriz de puntos',
			'Memoria RAM',
			'Mochilas',
			'Modems',
			'Monitores',
			'Motherboards',
			'Motherboards AMD',
			'Motherboards Intel',
			'Mouse Pad',
			'Multifuncionales',
			'Multimedia',
			'No breaks',
			'Notebooks',
			'Pads',
			'Palancas',
			'Palm',
			'Pantallas',
			'Pantallas LCD',
			'PC',
			'Pendrives',
			'Plotters',
			'RAM',
			'Reguladores',
			'Repuestos',
			'Router Inalambricos',
			'Routers Alambricos',
			'Routers WiFi',
			'scanners ',
			'Servidores de Impresion',
			'Sistema de tinta continua',
			'Sistemas Operativos',
			'Skins',
			'Sony',
			'Sony Vaio',
			'Swithces',
			'Tabletas digitales',
			'Tablets',
			'Tablets',
			'Tarjetas Controladoras',
			'Tarjetas de Edicion profesional',
			'Tarjetas de Red',
			'Tarjetas de red inalambrica',
			'Tarjetas de TV',
			'Tarjetas de Video',
			'Tarjetas Madre',
			'Tarjetas madre',
			'Tarjetas PCMCIA',
			'Termicas',
			'Torres duplicadoras de DVDs',
			'Toshiba',
			'Ventiladores',
		]
	},
	{
		'name':'Electrodomesticos',
		'tags':[
			'AEG',
			'Ariston',
			'Aspes',
			'Aspiradoras',
			'Balay',
			'Batidoras',
			'Bauknecht',
			'Beko',
			'Black&Decker',
			'Bosch',
			'Bose',
			'Cafeteras',
			'Campanas',
			'Candy',
			'Carrier',
			'Cata',
			'Cointra',
			'Corbero',
			'Daewood',
			'Daikin',
			'Daikin',
			'Edesa',
			'Electrolux',
			'Estufas y hornos',
			'Extractores de jugo',
			'Fagor',
			'Fleck',
			'Fujitsu',
			'GE',
			'General Electric',
			'Hewlett-Packard',
			'Hiyasu',
			'Hotsein',
			'IEM',
			'Ignis',
			'Indeist',
			'Junkers',
			'Kaysun',
			'Kenmore',
			'Lavadoras y secadoras',
			'LG',
			'Licuadoras',
			'Liebherr',
			'Lynx',
			'Mabe',
			'Manaur',
			'Maquinas de coser',
			'Microondas',
			'Miele',
			'Mitsubishi',
			'Ofsein',
			'Otros',
			'Panasonic',
			'Philco',
			'Philips',
			'Planchas',
			'Refrigeradores',
			'Roca',
			'Samsung',
			'Saunier Duval',
			'Sharp',
			'Siemens',
			'Teka',
			'Toshiba',
			'Vaillant',
			'Ventilacion y calefaccion',
			'Westinghouse',
			'Whirlpool',
		]
	},
	{
		'name':'Electronica y Accesorios',
		'tags':[
			'Accesorios para camaras',
			'Afga',
			'Alarmas',
			'Ambico',
			'Amplificadores',
			'Analogicas',
			'Aotuestereos con MP3',
			'Autoestereo con CD',
			'Autoestereo con MP3',
			'Autoestereos con CD',
			'Autoestereos',
			'Autoestero',
			'Baterias',
			'Baterias',
			'Baterias',
			'Benq',
			'Benro',
			'binoculares ',
			'Blackberry',
			'Bluetooth',
			'Bocinas',
			'Braun',
			'Bresser',
			'Bushnell',
			'Cables',
			'Cajas fuertes',
			'Calculadora cientifico',
			'calculadora graficadora',
			'Calculadora',
			'Camara analogica',
			'Camara de video analogica',
			'Camara de video digital',
			'Camara digital',
			'Camaras de seguridad',
			'Camaras de video',
			'Camaras de vigilancia',
			'camaras espia',
			'Camaras fotograficas',
			'Canon',
			'Capacitores',
			'Carcazas submarinas',
			'Cargadores',
			'Celestron',
			'Circuitos',
			'Cisco',
			'Control ',
			'Control remoto',
			'Controles remotos',
			'Controles',
			'Coolpix',
			'copiadora',
			'Davis & Stanford',
			'Daza',
			'Digital Security Controls',
			'Digitales',
			'DSC',
			'dvd portatil',
			'dvd portatiles',
			'Ecotrends',
			'Ecualizador',
			'Ecualizadores',
			'Epicentro',
			'Epicentros',
			'Epson',
			'Equipos',
			'Exotec',
			'Feisol',
			'Filtros',
			'Flashes',
			'Fujifilm',
			'Fundas y estuches',
			'Fundas',
			'Garret electronics',
			'GE',
			'General Electric',
			'Genius',
			'GeoVision',
			'Gitzo',
			'Gopro',
			'GPS',
			'grabador de dvd',
			'grabadores de dvd',
			'graficadora',
			'Hasselblad',
			'Hewlett-Packard',
			'HIK Vision',
			'Hitachi',
			'Home Theater',
			'Home Theaters',
			'Honeywell',
			'HP',
			'inmovilizadores electricos',
			'Ipad',
			'Ipod Touch',
			'Ipod',
			'Itouch',
			'Jessops',
			'JVC',
			'Kalimar',
			'Kingston',
			'Kingwave',
			'Kits de pilas',
			'Klip',
			'Kodak',
			'Konica Minolta',
			'Kowa',
			'LCD',
			'Lectores de memoria',
			'LED',
			'Leica',
			'Lentes',
			'Lexar',
			'Lexmark',
			'Lobo',
			'Loch',
			'Logitech',
			'Look',
			'Lugan',
			'Lumix',
			'Mamiya',
			'Manfrotto',
			'Mapas',
			'Markvision',
			'Maxwell',
			'Meade',
			'Memoria Flash',
			'Metz',
			'Microcontroladores',
			'Microprocesadores',
			'MicroSD',
			'Minicomponentes',
			'MiniSD',
			'Mitsubishi',
			'Modem',
			'modulador',
			'Modulos',
			'Monitores',
			'Monopies',
			'MP3',
			'MP4',
			'Nikon',
			'Nissin',
			'Nokia',
			'Olivetti',
			'Olympus',
			'Optex',
			'Orion',
			'Otros electronicos',
			'Otros',
			'Panasonic',
			'Panasonic',
			'Pantalla LCD',
			'Pantalla Plana',
			'Pantalla Plasma',
			'Pantallas',
			'Pantech',
			'Pelco',
			'Pentaflex',
			'Pentax',
			'Pilas',
			'PIMA',
			'Plasma',
			'Playbook',
			'PNY',
			'Polaroid',
			'Praktica',
			'Proyectores',
			'Quasar',
			'Ravelli',
			'Reflex-SLR',
			'Reproductor de DVD',
			'Ricoh',
			'Saba',
			'Sabrent',
			'sachtler-munchen',
			'Sakar',
			'Samsung',
			'Sandisk',
			'Sanyo',
			'SDHC',
			'Seafon',
			'Sekonic',
			'Sensomatic',
			'Sensores',
			'Sharp',
			'Shilba',
			'Siemens',
			'Sigma',
			'Silstar',
			'SilverHT',
			'Sky-watcher',
			'Sony',
			'Steren',
			'Subwoofers',
			'Sumax',
			'Swarovski',
			'Syscom',
			'Syscom',
			'Tableros',
			'Takashi',
			'Tamron',
			'Tarjeta madre',
			'Tarjeta SDHC',
			'Tarjetas de Captura',
			'Tarjetas de memoria',
			'Tasco',
			'TDK',
			'Telescopios ',
			'Televisiones',
			'Televisor LED',
			'Televisor portatil',
			'Televisores',
			'Thomson',
			'toners',
			'Toshiba',
			'Toshiba',
			'Toya',
			'Transmisor ',
			'Transmisor FM',
			'Tripies',
			'Tweeters',
			'Vangard Nivelo',
			'Velbon',
			'Verbatlm',
			'View Sonic',
			'Vivitar',
			'Woofers',
			'Yashica',
			'Zebra',
			'Zeikos',
			'Zenit',
			'ZigBee',
			'Zune',
		]
	},
	{
		'name':'Hogar',
		'tags':[
			'AC',
			'Accesorios',
			'Accesorios',
			'Adornos',
			'Aire Acondicionado',
			'Aires Acondicionados',
			'Alfombras ',
			'Asador',
			'Asadores',
			'Bares',
			'bases.',
			'Baño',
			'Baño',
			'Billar',
			'Blancos',
			'Caja fuerte',
			'Cajas fuertes',
			'Camas',
			'Cantinas',
			'Cocina',
			'Cocina',
			'Cojines',
			'colchones ',
			'Comedor',
			'Comedores',
			'corrales para bebe.',
			'Cortinas',
			'Cuadros',
			'Cunas',
			'Decoracion  ',
			'Decoracion y accesorios para el  hogar',
			'Decoracion',
			'Decoracion',
			'Exterior ',
			'Floreros',
			'iluminacion',
			'Interiores',
			'Jardin',
			'Lampara',
			'Lamparas para exterior',
			'Lamparas para interior',
			'Lamparas',
			'Lavabos',
			'Libreria',
			'Librerias',
			'Librero',
			'Libreros',
			'Luces',
			'Maceta',
			'Macetas',
			'Mesa de billar',
			'Mesas de comedor',
			'moises ',
			'Muebles de baño',
			'Muebles de cocina',
			'muebles infantiles',
			'Muebles',
			'Ovalines',
			'Parrilla',
			'Parrillas',
			'Partes de comedor',
			'Piso',
			'Pisos',
			'Pisos',
			'Planta',
			'Plantas',
			'Puf',
			'Puff',
			'Puffs',
			'Pufs',
			'Recamara',
			'Recamara',
			'Recamaras',
			'Recamaras',
			'Reloj de pared',
			'Reloj',
			'Relojes de pared',
			'Relojes',
			'Sala de estar',
			'Sala',
			'Salas',
			'tapetes ',
			'Utensilios',
		]
	},
	{
		'name': 'Instrumentos Musicales',
		'tags':[
			'Accesorios ',
			'Accesorios',
			'Accesorios',
			'Acordeones',
			'Acustica electrica',
			'Acustica',
			'Amplificadores',
			'Amplificadores',
			'Armonicas',
			'Baterias',
			'Baterias',
			'Clarinetes',
			'Consolas y mezcladoras',
			'Electrica',
			'Flautas',
			'Guitarras',
			'Instrumentos de viento',
			'Libros',
			'Microfonos',
			'Partes y Accesorios',
			'Partituras y tablaturas',
			'percusion',
			'Pianos',
			'Plumillas',
			'Saxofones',
			'Teclados',
			'Trompetas',
			'Violin',
		]
	},
	{
		'name':'Joyas y Relojes',
		'tags':[
			'Accesorios',
			'anillos',
			'Anillos',
			'Anillos',
			'Aras',
			'Aretes ',
			'boda',
			'cadenas',
			'collares',
			'Compromiso',
			'Gargantillas ',
			'Hombre',
			'Joyeria de fantasia',
			'Joyeria fina',
			'Mujer',
			'Otros',
			'pulseras.',
			'Relojes',
			'Relojes',
		]
	},
	{
		'name':'Juguetes',
		'tags':[
			'Adultos',
			'albercas',
			'Bebes',
			'Brincolines',
			'Disfraces',
			'Juegos de mesa',
			'Juguetes',
			'Muñecas',
			'Muñecos',
			'Niñas',
			'Niños',
			'Niños y bebes',
			'Osos de peluche',
		]
	},
	{
		'name':'Libros y Revistas',
		'tags':[
			'Adolescentes',
			'Arquitectura',
			'Arte',
			'Atlas',
			'Audio libros',
			'Autoayuda',
			'Biografías',
			'Ciencias economicas',
			'Ciencias exactas',
			'Ciencias humanisticas',
			'Ciencias medicas',
			'Ciencias naturales',
			'Ciencias sociales',
			'Comics',
			'Computacion',
			'DC',
			'Diccionarios',
			'Diseño',
			'Economia',
			'Editoriales nacionales',
			'Educativos',
			'Enciclopedias',
			'Escolares',
			'Esoterismo',
			'Femeninas',
			'Ficcion',
			'Fisica',
			'Hobbies',
			'Idiomas',
			'Infantiles',
			'Interes general',
			'Internet',
			'Libros tecnicos',
			'Libros',
			'Literatura clasica',
			'Literatura',
			'Manga',
			'Manuales',
			'Marvel',
			'Matematicas',
			'Medicina',
			'musica',
			'Niños',
			'Oficios',
			'Otros ',
			'Quimica',
			'Recetarios',
			'Recreacion',
			'Religion',
			'Revistas',
			'Spawn',
			'Star Wars',
			'Temas especificos',
			'videojuegos',
		]
	},
	{
		'name':'Peliculas, series y DVDs',
		'tags':[
			'Peliculas',
			'Accion',
			'Alternativa',
			'Animadas',
			'Anime',
			'Autoayuda',
			'Aventuras',
			'Blu-ray',
			'Blues',
			'Caricaturas',
			'Ciencia ficcion',
			'Clasicas',
			'Comedia',
			'Comedia',
			'Cumbia',
			'Dance',
			'Deportes',
			'Documentales ',
			'Drama',
			'DVD',
			'Electronica',
			'Entrevistas',
			'Extranjeras',
			'Ficcion',
			'Ficcion',
			'Funk',
			'Hardcore',
			'Heavy Metal',
			'Hip Hop',
			'Infantiles',
			'Intrumental',
			'Jazz',
			'Merengue',
			'Musica',
			'Nacionales',
			'Otros generos',
			'Otros',
			'Para toda la familia',
			'Pop',
			'Punk',
			'Reggae',
			'Rock',
			'Salsa',
			'Series',
			'Show de television',
			'Ska',
			'Sony',
			'Sountracks',
			'Suspenso',
			'Terror',
			'Trash',
		]
	},
	{
		'name':'Ropa y Accesorios',
		'tags':[
			'Abrigos y chaquetas',
			'Accesorios de mujer',
			'Accesorios para caballero',
			'Bebe',
			'Blusas ',
			'Blusas',
			'Bolsas',
			'Botas',
			'Caballero',
			'Camisas casuales',
			'Camisas formales',
			'Camisas',
			'Carteras',
			'Casual ',
			'Cintos',
			'Cintos',
			'Damas',
			'Deportiva',
			'Deportiva',
			'Faldas',
			'Formal de piso',
			'Interior y de dormir',
			'Invierno',
			'jeans',
			'Jeans',
			'Lentes de sol',
			'Lentes de sol',
			'Mascadas',
			'Mochilas',
			'Niña',
			'Niño',
			'Otros',
			'Pantalones',
			'Pantalones',
			'Pantalones',
			'Pantalones',
			'Ropa de Invierno',
			'Ropa Deportiva',
			'Sacos y Chalecos',
			'Sandalias',
			'Shorts',
			'Sombreros',
			'Sombreros',
			'Sudaderas',
			'Tenis',
			'Vestidos y faldas',
			'Vestidos',
			'Zapatillas',
			'Zapato de vestir',
			'Zapato formal',
		]
	},
	{
		'name':'VideoJuegos',
		'tags':[
			'Nintendo Wii ',
			'Nintendo Wii U',
			'Wii',
			'Wii U',
			'Juegos',
			'Consolas',
			'Wii remote',
			'Wiimote',
			'Nunchuck',
			'Wii motion Plus',
			'Fundas',
			'Correas',
			'Accesorios',
			'Controles',
			'Nintendo 3DS',
			'Nintendo DSi',
			'Nintendo SP ',
			'Nintendo DS',
			'Nintendo 3DS XL',
			'Estuche',
			'Stylus',
			'Plumita',
			'Cargadores',
			'Cargador',
			'Nintendo Gamecube',
			'Game cube',
			'Memory Cards',
			'Memory Card',
			'Nintendo 64',
			'Memory pack',
			'Expansion Pack',
			'Rumble pack',
			'Transfer pack',
			'Gameboy',
			'Gameboy Advance',
			'Gameboy Color',
			'Gameboy pocket',
			'game boy',
			'Super Nintendo',
			'Famicom',
			'Family Computer',
			'Dreamcast',
			'xbox',
			'x box',
			'xbox 360',
			'x box 360',
			'Kinect',
			'Audifonos',
			'Microfonos',
			'Microfono',
			'Playstation',
			'Play station 1',
			'PS one',
			'Psone',
			'Playstation 2',
			'Ps2',
			'Playstation 3',
			'Ps3',
			'Playstation Move',
			'PS eye',
			'Otros',
			'PSP',
			'PSP Vita',
			'Play station portable',
			'Playstation portable',
			'Playstation 4',
			'Accion',
			'Automovilismo',
			'Atumoviles',
			'Autos',
			'Aventura',
			'Deportes',
			'FIFA',
			'Estrategia',
			'RPG',
			'Otros Juegos',
			'Maquinitas',
			'Chispas',
			'Maquinas multijuegos',
			'SNES',
			'NES',
			'Sega Genesis',
			'Genesis',
			'Nintendo NES',
			'Guitar Hero',
			'Rockbanbd',
			'Rock Band',
			'GuitarHero',
			'GH',
			'RB',
		]
	}
]